[package]
name = "zjstatus"
version = "0.3.1"
authors = ["Daniel Jankowski"]
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
zellij-tile = "0.38.0"
chrono = "0.4.0"
regex = "1.9.4"
strip-ansi-escapes = "0.2.0"
chrono-tz = "0.8.3"
anyhow = "1.0.75"
