on: push
name: Test & Lint

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: '1.76.0'
          profile: minimal
          override: true
          target: wasm32-wasi
          components: clippy

      - name: Run Clippy
        uses: clechasseur/rs-clippy-check@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jcbhmr/setup-wasmtime@v2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: '1.76.0'
          profile: minimal
          override: true
          target: wasm32-wasi

      - name: Install cargo wasi
        run: cargo install cargo-wasi

      - name: Run tests
        run: cargo wasi test --lib -- --nocapture
